default: &default
  app_key: 09h8a7jahnq10a2
  app_secret: 3wt2gpfbwdvv69m
  user_id: 254396985
  access_type: app_folder

production:
  <<: *default
  access_token: jiehlhg9743jm9wr
  access_token_secret: bijowa45v9jmjtv

development:
  <<: *default
  access_token: vkvpvmm40qtk787c
  access_token_secret: o7zmb4yxq1x7tgb